# Generated by Django 4.2 on 2024-03-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_user_name_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='category name'),
        ),
    ]
